mysite/login/urls.py
from django.conf.urls import url

from . import views

from .models import User

app_name = 'login'

urlpatterns = [
    url(r'^$', views.login, name='login_home'),
    url(r'^register$', views.register, name='register'),
    url(r'^loginout$', views.loginout, name='loginout'),
    url(r'^index$', views.LoginIndex.as_view(), name='loginindex'),
]

mysite/myself/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^resume/', include('resume.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
    # url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),


]

mysite/resume/urls.py
from django.conf.urls import url

from . import views

from .models import BasicInformation

app_name = 'resume'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home$', views.IndexView.as_view(), name='index_home'),
    url(r'^award$', views.AwardView.as_view(template_name="resume/award.html"), name='award'),
    url(r'^index-template-view$', views.IndexTemplateView.as_view(), name='index-template-view'),
]

mysite/resume/models.py
from django.db import models

# Create your models here.

class BasicInformation(models.Model):
    name = models.CharField(max_length=50)
    education = models.CharField(max_length=50)
    school = models.CharField(max_length=50)
    major = models.CharField(max_length=50)
    
    def __str__(self):
        return '{}/{}'.format(self.name, self.education)

class Award(models.Model):
    basic_information = models.ForeignKey(BasicInformation, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    time = models.DateField(verbose_name='time of award')

    def __str__(self):
        return self.name

class Transcript(models.Model):
    basic_information = models.ForeignKey(BasicInformation, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    score = models.IntegerField(default=0)
    
    def __str__(self):
        return self.subject

mysite/resume/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render

# Create your views here.

from django.http import HttpResponseRedirect
from django.views import generic
from .models import BasicInformation
from myself.settings import LOGIN_URL

class IndexView(generic.ListView):
    model = BasicInformation
    template_name = "resume/index.html"
    context_object_name = "basic_information_list"

from django.contrib.auth.decorators import login_required


def index(request):
    if 'user' in request.session:
        return render(request, 'resume/index.html',
            context={'basic_information_list': BasicInformation.objects.all(),
                'username': request.session['user']}
        )
    else:
        return HttpResponseRedirect(LOGIN_URL)


class AwardView(generic.ListView):
    model = BasicInformation
    context_object_name = "basic_information_list"


def award(request):
    return render(request, 'resume/award.html',
        context={'basic_information_list': BasicInformation.objects.all()}
    )


class IndexTemplateView(generic.TemplateView):
    template_name = "resume/index-template-view.html"
    
    def get_context_data(self, **kwargs):
        context = super(IndexTemplateView, self).get_context_data(**kwargs)
        context['basic_information_list'] = BasicInformation.objects.all()
        return context

mysite/resume/templates/resume/award.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'resume/style.css' %}" />

<a href='{% url 'resume:index' %}'>My Resume</a><br/>

<a href='{% url 'resume:award' %}'>My Award</a><br/>

<a href='{% url 'resume:index-template-view' %}'>IndexTemplateView</a>

{% if basic_information_list %}
    <ul>
        {% for basic_information in basic_information_list %}
            <li>{{ basic_information.education }}</li>
            <ul type="disc">
                {% for award in basic_information.award_set.all %}
                    <li>{{ award.name }}, {{ award.time }}</li>
                {% endfor %}
            </ul>
        {% endfor %}
    <ul>
{% else %}
    <li>No resumes are available</li>
{% endif %}

mysite/resume/templates/resume/index-template-view.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'resume/style.css' %}" /> 

<img src= "{% static "resume/images/RedHat.png" %}" alt="My image"/><br/>

<a href='{% url 'resume:index' %}'>My Resume</a><br/>

<a href='{% url 'resume:award' %}'>My Award</a><br/>

<a href='{% url 'resume:index-template-view' %}'>IndexTemplateView</a>

{% if basic_information_list %}
    <ul>
        {% for basic_information in basic_information_list %}
            <li>{{ basic_information.education }}</li>
        {% endfor %}
    </ul>
{% else %}
    <li>No basic information are available</li>
{% endif %}

mysite/resume/templates/resume/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'resume/style.css' %}"/> 

<body>
    <div class="right">
        <a> {{username}} </a><br/>
        <a href='{% url 'polls:index' %}'>Polls</a><br/>
    </div>
    <div class="center">
        <img src= "{% static "resume/images/RedHat.png" %}" alt="My image"/><br/>
        <a href='{% url 'resume:index' %}'>My Resume</a><br/>
        <a href='{% url 'resume:award' %}'>My Award</a><br/>
        <a href='{% url 'resume:index-template-view' %}'>IndexTemplateView</a>
        {% if basic_information_list %}
            <ul>
                {% for basic_information in basic_information_list %}
                    <li>{{ basic_information.education }}</li>
                {% endfor %}
            </ul>
        {% else %}
            <li>No basic information are available</li>
        {% endif %}
    </div>
</body>