mysite/login/urls.py
from django.conf.urls import url

from . import views

from .models import User

app_name = 'login'

urlpatterns = [
    url(r'^$', views.login, name='login_home'),
    url(r'^register$', views.register, name='register'),
    url(r'^loginout$', views.loginout, name='loginout'),
    url(r'^index$', views.LoginIndex.as_view(), name='loginindex'),
]

mysite/myself/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^resume/', include('resume.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/resume/urls.py
from django.conf.urls import url

from . import views

from .models import BasicInformation

app_name = 'resume'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home$', views.IndexView.as_view(), name='index_home'),
    url(r'^award$', views.AwardView.as_view(template_name="resume/award.html"), name='award'),
    url(r'^index-template-view$', views.IndexTemplateView.as_view(), name='index-template-view'),
]

mysite/login/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.username

mysite/login/views.py
from django.shortcuts import render

# Create your views here.

from django.views import generic
from .models import User

from django import forms
from django.http import HttpResponseRedirect
from django.http import HttpResponse


class UserForm(forms.Form):
    username = forms.CharField(label='username', max_length=100)
    password = forms.CharField(label='password', widget=forms.PasswordInput())


def register(request):
    if request.method == 'POST':
        uf = UserForm(request.POST)
        if uf.is_valid():
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            user = User.objects.filter(username__exact=username)
            print(user)
            if user:
                return HttpResponse(username + ' already exists')
            else:
                user = User()
                user.username, user.password = username, password
                user.save()
                return HttpResponseRedirect('/login/')
        else:
            return HttpResponseRedirect('/login/register/')
    else:
        uf = UserForm()
    return render(request, 'login/register.html', {'uf': uf})

def login(request):
    request.session['login_from'] = request.META.get('HTTP_REFERER', '/')
    if request.method == 'POST':
        uf = UserForm(request.POST)
        if uf.is_valid():
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            user = User.objects.filter(username__exact=username,
                password__exact = password)
            if user:
                request.session['user'] = username
                return HttpResponseRedirect('/resume/')
                """
                return render(
                    request, 'login/success.html', 
                    {'user_list': User.objects.all()})
                """
            else:
                return HttpResponseRedirect('/login/')
    else:
        uf = UserForm()
    return render(request, 'login/login.html', {'uf': uf})


def loginout(request):
    if 'user' in request.session:
        print('user: %s' %request.session['user'])
        del request.session['user']
    else:
        print('loginout')
    return HttpResponseRedirect('/login/')

class LoginIndex(generic.TemplateView):
    template_name = "login/index.html"

    def get_context_data(self, **kwargs):
        context = super(LoginIndex, self).get_context_data(**kwargs)
        context['user_list'] = User.objects.all()
        return context
    

mysite/login/templates/login/index.html
{% if user_list %}
    <ul>
        {% for user in user_list %}
            <li>{{ user.username }}</li>
        {% endfor %}
    </ul>
{% else %}
    <li>No usernames</li>
{% endif %}

mysite/login/templates/login/login.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'login/general.css' %}"/>

<title>Welcome On Board</title>
<body>
    <div class="center">
        <p>Welcome On Board</p>
        <form method = 'post' enctype="multipart/form-data">
            {% csrf_token %}  
            {{uf.as_p}}
            <input type="submit" value = "Board" />
        </form>
    <a href="{% url 'login:register' %}">Register</a>
    </div>
{# <input type="hidden" name="next" value="/resume/" /> #}
</body>

mysite/login/templates/login/register.html
{% load static %}

{% comment%}
<link rel="stylesheet" type="text/css" href="{% static 'login/register.css' %}"/>
{% endcomment%}

<link rel="stylesheet" type="text/css" href="{% static 'login/register.css' %}"/>

<title>Register</title>
<body>
    <div class="center">
        <p>Register</p>
        <form method = 'post' enctype="multipart/form-data">
            {% csrf_token %}  
            {{uf.as_p}}
            <input type="submit" value = "ok" />
        </form>

        <a href='{% url 'login:login_home' %}'>Login</a>
    </div>
</body>

mysite/login/templates/login/success.html
<title>Welcome On Board</title>
<p>Welcome On Board</p>

<p>All registered users</p>
{% if user_list %}
    <ul>
        {% for user in user_list %}
            <li>{{ user.username }}</li>
        {% endfor %}
    </ul>
{% else %}
    <li>No usernames</li>
{% endif %}

<a href="{% url 'resume:index' %}">Resume</a>